version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-1-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile --no-progress

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-1-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: "."
          paths:
            - ./*
            - node_modules
            - yarn.lock
            - src

  lint:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: "."

      - run: yarn run lint

  publish:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: "."

      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

      - run: npm publish || exit 0

  prettier:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: "."

      - run: yarn run prettier

  test:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: "."

      - run: yarn run test:ci

  compile:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: "."

      - run: yarn run compile

      - persist_to_workspace:
          root: "."
          paths:
            - src

workflows:
  version: 2
  commit:
    jobs:
      - build
      - compile:
          requires:
            - build
      - lint:
          requires:
            - build
      - publish:
          context: org-global
          filters:
            branches:
              only: main
          requires:
            - compile
      - prettier:
          requires:
            - build
      - test:
          requires:
            - build
